define(['mithril','titar'], function(n,t){

    var Localisation = {
		"list":{
			"pl-PL":"PL",
			"ru-RU":"RU",
			"en-GB":"EN",
		},
        "currentLanguage":"ru",
		"dictionary":{
			"NAME":"NAME",
			"STATUS":"STATUS",
			"LAST_CONTACT":"LAST_CONTACT",
			"NOTE":"NOTE",
			"CONTACTS":"CONTACTS",
			"CONTACT":"CONTACT",
			"MANAGE":"MANAGE",
			"SEARCH":"SEARCH",
			"EDIT":"EDIT",
			"TODAY":"TODAY",
			"YESTERDAY":"YESTERDAY",
			"SITE":"SITE",
			"LOGIN":"LOGIN",
			"PASSWORD":"PASSWORD",
			"SAVE":"SAVE",
			"BACK":"BACK",
			"FIRSTNAME":"FIRSTNAME",
			"LASTNAME":"LASTNAME",
			"EMAIL":"EMAIL",
			"PHONE":"PHONE",
			"ADD":"ADD",
			"DATE_OF_CONTACT":"DATE_OF_CONTACT",
			"PROFILE":"PROFILE",
			"COMMENTS":"COMMENTS",
			"SEND":"SEND",
			"WRITE_A_COMMENT":"WRITE_A_COMMENT",
			"TITUL":"TITUL",
			"NONE":"NONE",
			"ABSENT":"ABSENT",
			"REMOVE":"REMOVE",
			"MORE":"MORE",
			"STATUS_CHANGE":"STATUS_CHANGE",
			"PHOTO":"PHOTO",


			"CLIENT_NAME":"CLIENT_NAME",
			"CLIENT_NEW":"CLIENT_NEW",
			"CLIENT_EDIT":"CLIENT_EDIT",
			"CLIENT_DELETE":"CLIENT_DELETE",
			"CLIENT_UPDATE_LAST_CONTACT":"CLIENT_UPDATE_LAST_CONTACT",
			"CLIENT":"CLIENT",
			"CLIENTS":"CLIENTS",

			"PROJECT":"PROJECT",
			"PROJECTS":"PROJECTS",
			"PROJECT_NEW":"PROJECT_NEW",
			"PROJECT_DELETE":"PROJECT_DELETE",

			"TASK":"TASK",
			"TASKS":"TASKS",
			"MY_TASKS":"MY_TASKS",
			"TASK_EDIT":"TASK_EDIT",
			"TASK_NEW":"TASK_NEW",

			"TAGS":"TAGS",

			"EMPLOYEE_DELETE":"EMPLOYEE_DELETE",
			"EMPLOYEES":"EMPLOYEES",
			"EMPLOYEE_NEW":"EMPLOYEE_NEW",
			"EMPLOYEE_ATTACH":"EMPLOYEE_ATTACH"
		}
    }

    return Localisation;
});
